languageCode = "en-gb"
title = "Edmonds Commerce Docs"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true

[params]
	# General information
	author = "Edmonds Commerce"
	description = "A material design theme for documentations configured for Edmonds Commerce."
	copyright = "Released under the MIT license"

	version = "1.0.0"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	[params.palette]
    	primary = "red"
    	accent  = "teal"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"



[[menu.main]]
	name   = "Adding content"
	url    = "adding-content/"
	weight = 20